### ISSUE TITLE
05/27/2022 - Formal Meeting, Project Discussion, & Finalization of Tasks and Roles

### ISSUE THREAD

**Issue by pvmhae-alcoran** [pvmhae-alcoran/E-E-Exam#1]
Hello guys! Interact here

**Comment by beadanlag** [comment]
hi!

**Comment by pvmhae-alcoran** [comment]
Okay na 'yong inassign ko sa'yo, bey?

**Comment by beadanlag** [comment]
inaayos pa po

**Comment by pvmhae-alcoran** [comment]
okiess! good good

**Comment by daeldaeho** [comment]
hellooo
leader nagawa ko na po ang part na inassign mo saakin

**Comment by pvmhae-alcoran** [comment]
okiess good good,, pa update sa user interface na issue 'yong progress mooo, dale! para makita natin lahat

**Comment by daeldaeho** [comment]
okay okay po

**Comment by vego-eubewt** [comment]
small errors nalang po, pero ma fix naman sha tonight let's discuss nalang later

**Comment by pvmhae-alcoran** [comment]
Thank you sa pag-interact guys! Ito final roles and tasks naten ha

Group Members: Task and Roles

ALCORAN, PV Mhae B. 

- Team Leader
- Manage the Repository
- Working on Codes

VEGO, EUBERT MARTIN

- Main coder
- Stopwatch Logic

VINSON, CHRISTIAN DALE

- User Interface Design
- Working on Codes

DANLAG, BEA

- Documentation (Records the discussion/meeting)
- Coder

Let us work together guys oki! Aja!

**Comment by pvmhae-alcoran** [comment]
ano na final name naten guysZz? any thotssss

**Comment by vego-eubewt** [comment]
ummm lets use our initials

**Comment by pvmhae-alcoran** [comment]
sureee eubsss

**Comment by vego-eubewt** [comment]
or maybe gusto niyo euberts crew hihi

**Comment by beadanlag** [comment]
DAVE

Danlag
Alcoran
Vinson
Eubert

**Comment by pvmhae-alcoran** [comment]
ediwow HAHAHHA

**Comment by vego-eubewt** [comment]
or

**Comment by vego-eubewt** [comment]
BEACH Bea Eubert Alcoran CHristian

**Comment by pvmhae-alcoran** [comment]
wawww nice idea HAHAHA

**Comment by beadanlag** [comment]
pwede naman BEACH

**Comment by vego-eubewt** [comment]
baka may other suggestions pa

**Comment by daeldaeho** [comment]
for me pwede naman yung BEACH

**Comment by daeldaeho** [comment]
or pwede ding d'ped

**Comment by daeldaeho** [comment]
DPED (dale pv eubert danlag)

**Comment by vego-eubewt** [comment]
nice shaaa

**Comment by vego-eubewt** [comment]
leader ano masabi mo okay na ako sa D'PED

**Comment by pvmhae-alcoran** [comment]
final na yan ahhh

**Comment by pvmhae-alcoran** [comment]
Ahensya ng gobyerno lang ang peg? HAHAHAH char eme
