### ISSUE TITLE
UPDATES ON THE USER INTERFACE

### ISSUE THREAD

**Issue by pvmhae-alcoran** [pvmhae-alcoran/E-E-Exam#2]

**Comment by daeldaeho** [comment]
eto na pala ang initial na interface ng stopwatch nati
![280835543_1046186636297465_8221668101145269142_n](https://user-images.githubusercontent.com/105418304/170718795-dd247c09-2621-4b68-a6aa-76138d34356c.png)
n

**Comment by daeldaeho** [comment]
okay na ba ito??

**Comment by daeldaeho** [comment]
try ko lang icode ulit para mas mapaganda

**Comment by pvmhae-alcoran** [comment]
thanks, dale! konteng ayos nalang tas goods na yan.

**Comment by pvmhae-alcoran** [comment]
daleeee,, may update na ba u?

**Comment by daeldaeho** [comment]
yes meron update

**Comment by daeldaeho** [comment]
![Uploading IMG_20220529_005419.JPG…]()

**Comment by daeldaeho** [comment]
eto ang bagong interface ng stop watch

**Comment by daeldaeho** [comment]
![Uploading IMG_20220529_005419.JPG…]()

**Comment by vego-eubewt** [comment]
i cant seem to view the image dale

**Comment by daeldaeho** [comment]
wait lang theres an issue

**Comment by pvmhae-alcoran** [comment]
Okii, dale. No pressure ah. Willing to wait man ang all

**Comment by daeldaeho** [comment]
![281161981_3228486867367137_2203489992015065626_n](https://user-images.githubusercontent.com/105418304/170835360-bbe97895-f663-413d-ab8e-150d92997f02.png)

**Comment by daeldaeho** [comment]
any suggestions guys

**Comment by pvmhae-alcoran** [comment]
huwawser HAHAHAHA bat dalawa lang buttons? pa explain pii kung ano nagbago

**Comment by vego-eubewt** [comment]
saan na ang stop and reset? yan ba yung naga change kung iclick?

**Comment by pvmhae-alcoran** [comment]
maybee? wait naten explanation ni dale baka mabagal signal nila

**Comment by daeldaeho** [comment]
yep nagachange sya if iclick guys

**Comment by daeldaeho** [comment]
sorry ngayon lang nakareply. medjo mahina net ngayon kasi umuulan samin

**Comment by daeldaeho** [comment]
nagchachange yung start button into stop button at yung reset into button lap button

**Comment by daeldaeho** [comment]
suggest guys if may gusto pa kayong ichange para sa ikagaganda ng project

**Comment by daeldaeho** [comment]
ang bagong interface natin guys parang nirelate sa mga stopwatch na ginagamit sa sports like swimming and track and field

**Comment by pvmhae-alcoran** [comment]
wowwwww sigi sigiii,, meet tayoo later tas present mo lang at explain samen. thanksss dalee!

**Comment by daeldaeho** [comment]
okieee dokiee. no problem
