### ISSUE TITLE
ERRORS ON THE CODES

### ISSUE THREAD

**Issue by pvmhae-alcoran** [pvmhae-alcoran/E-E-Exam#3]

**Comment by vego-eubewt** [comment]
im having a hard time figuring out how to work with specialized buttons

**Comment by pvmhae-alcoran** [comment]
go eubs! kaya yan ahhh

**Comment by vego-eubewt** [comment]
finally fixed the buttons, id love to discuss it with you during our next online meeting

**Comment by pvmhae-alcoran** [comment]
good work, eubs!

**Comment by vego-eubewt** [comment]
thankksss
