### ISSUE TITLE
UPDATES ON THE DOCUMENTATIONS

### ISSUE THREAD

**Issue by pvmhae-alcoran** [pvmhae-alcoran/E-E-Exam#4]

**Comment by beadanlag** [comment]
### **MAY 27, 2022**
 **Meeting through GMEET**
Tasks Completed:

- [x] explaining the codes
![Screenshot_5](https://user-images.githubusercontent.com/105398940/170835660-f46b67d5-108b-4f7b-aa56-51d685c7aba3.png)


- [x] discussing the user interface
### ### 
![Screenshot_6](https://user-images.githubusercontent.com/105398940/170835490-8f514a27-4345-489d-8c02-b667f78fe804.png)

**Comment by pvmhae-alcoran** [comment]
thank you for this bey! good work
